name: Unit Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  unittest:
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        platform: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install PIP
      run: |
        python -m pip install --upgrade pip
    - name: Install dependencies
      run: |
        python -m pip install poetry
        poetry update --lock
        poetry install
    - name: Lint
      run: |
        poetry run sh scripts/lint.sh
    - name: Tests
      run: |
        poetry run sh scripts/unittest.sh
